# Generated by Django 2.0.7 on 2018-07-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
